let warframes = [
    {
        name: "Ash",
        health: 150,
        shield: 100,
        armor: 100,
        sprintSpeed: 1.15,
        energy: 100,
        duration: 100,
        efficiency: 100,
        range: 100,
        strength: 100,
        ability1: "/abilityIcons/ash/NinjaStar.png.webp",
        ability2: "/abilityIcons/ash/NinjaSmokeScreen.png.webp",
        ability3: "/abilityIcons/ash/NinjaTeleport.png.webp",
        ability4: "/abilityIcons/ash/NinjaStorm.png.webp"
    },{
        name: "Ash Prime",
        health: 150,
        shield: 125,
        armor: 175,
        sprintSpeed: 1.2,
        energy: 100,
        duration: 100,
        efficiency: 100,
        range: 100,
        strength: 100,
        ability1: "/abilityIcons/ash/NinjaStar.png.webp",
        ability2: "/abilityIcons/ash/NinjaSmokeScreen.png.webp",
        ability3: "/abilityIcons/ash/NinjaTeleport.png.webp",
        ability4: "/abilityIcons/ash/NinjaStorm.png.webp"
    },{
        name: "Atlas",
        health: 100,
        shield: 100,
        armor: 450,
        sprintSpeed: 0.9,
        energy: 150,
        duration: 100,
        efficiency: 100,
        range: 100,
        strength: 100,
        ability1: "/abilityIcons/atlas/AtlasRockPunch.png.webp",
        ability2: "/abilityIcons/atlas/AtlasBarrier.png.webp",
        ability3: "/abilityIcons/atlas/AtlasStoneGaze.png.webp",
        ability4: "/abilityIcons/atlas/AtlasSummon.png.webp"
    },{
        name: "Atlas Prime",
        health: 175,
        shield: 150,
        armor: 475,
        sprintSpeed: 1,
        energy: 175,
        duration: 100,
        efficiency: 100,
        range: 100,
        strength: 100,
        ability1: "/abilityIcons/atlas/AtlasRockPunch.png.webp",
        ability2: "/abilityIcons/atlas/AtlasBarrier.png.webp",
        ability3: "/abilityIcons/atlas/AtlasStoneGaze.png.webp",
        ability4: "/abilityIcons/atlas/AtlasSummon.png.webp"
    },{
        name: "Banshee",
        health: 100,
        shield: 100,
        armor: 100,
        sprintSpeed: 1.1,
        energy: 150,
        duration: 100,
        efficiency: 100,
        range: 100,
        strength: 100,
        ability1: "/abilityIcons/banshee/BansheeSonicBoom.png.webp",
        ability2: "/abilityIcons/banshee/BansheeSonar.png.webp",
        ability3: "/abilityIcons/banshee/BansheeSilence.png.webp",
        ability4: "/abilityIcons/banshee/BansheeSoundQuake.png.webp"
    },{
        name: "Banshee Prime",
        health: 100,
        shield: 100,
        armor: 125,
        sprintSpeed: 1.15,
        energy: 175,
        duration: 100,
        efficiency: 100,
        range: 100,
        strength: 100,
        ability1: "/abilityIcons/banshee/BansheeSonicBoom.png.webp",
        ability2: "/abilityIcons/banshee/BansheeSonar.png.webp",
        ability3: "/abilityIcons/banshee/BansheeSilence.png.webp",
        ability4: "/abilityIcons/banshee/BansheeSoundQuake.png.webp"
    },{
        name: "Baruuk",
        health: 75,
        shield: 100,
        armor: 175,
        sprintSpeed: 1.2,
        energy: 200,
        duration: 100,
        efficiency: 100,
        range: 100,
        strength: 100,
        ability1: "/abilityIcons/baruuk/BaruukBulletDodger.png.webp",
        ability2: "/abilityIcons/baruuk/BaruukCalmingWave.png.webp",
        ability3: "/abilityIcons/baruuk/BaruukOrbitalDisarm.png.webp",
        ability4: "/abilityIcons/baruuk/BaruukOverTheEdge.png.webp"
    },{
        name: "Baruuk Prime",
        health: 75,
        shield: 125,
        armor: 225,
        sprintSpeed: 1.2,
        energy: 200,
        duration: 100,
        efficiency: 100,
        range: 100,
        strength: 100,
        ability1: "/abilityIcons/baruuk/BaruukBulletDodger.png.webp",
        ability2: "/abilityIcons/baruuk/BaruukCalmingWave.png.webp",
        ability3: "/abilityIcons/baruuk/BaruukOrbitalDisarm.png.webp",
        ability4: "/abilityIcons/baruuk/BaruukOverTheEdge.png.webp"
    },{
        name: "Caliban",
        health: 100,
        shield: 175,
        armor: 275,
        sprintSpeed: 1.1,
        energy: 125,
        duration: 100,
        efficiency: 100,
        range: 100,
        strength: 100,
        ability1: "/abilityIcons/caliban/CalibanWhirlwind.png.webp",
        ability2: "/abilityIcons/caliban/CalibanShockwave.png.webp",
        ability3: "/abilityIcons/caliban/CalibanSummonSentients.png.webp",
        ability4: "/abilityIcons/caliban/CalibanTriLaser.png.webp"
    },{
        name: "Chroma",
        health: 100,
        shield: 100,
        armor: 350,
        sprintSpeed: 1,
        energy: 150,
        duration: 100,
        efficiency: 100,
        range: 100,
        strength: 100,
        ability1: "/abilityIcons/chroma/DragonElementalAttack.png.webp",
        ability2: "/abilityIcons/chroma/DragonLuckyDragon.png.webp",
        ability3: "/abilityIcons/chroma/DragonDragonScales.png.webp",
        ability4: "/abilityIcons/chroma/DragonSentient.png.webp"
    },{
        name: "Chroma Prime",
        health: 100,
        shield: 100,
        armor: 425,
        sprintSpeed: 1,
        energy: 200,
        duration: 100,
        efficiency: 100,
        range: 100,
        strength: 100,
        ability1: "/abilityIcons/chroma/DragonElementalAttack.png.webp",
        ability2: "/abilityIcons/chroma/DragonLuckyDragon.png.webp",
        ability3: "/abilityIcons/chroma/DragonDragonScales.png.webp",
        ability4: "/abilityIcons/chroma/DragonSentient.png.webp"
    },{
        name: "Citrine",
        health: 135,
        shield: 100,
        armor: 250,
        sprintSpeed: 1,
        energy: 120,
        duration: 100,
        efficiency: 100,
        range: 100,
        strength: 100,
        ability1: "/abilityIcons/citrine/FracturedBlast130xWhite.webp",
        ability2: "/abilityIcons/citrine/PreservingShell130xWhite.webp",
        ability3: "/abilityIcons/citrine/PrismaticGem130xWhite.webp",
        ability4: "/abilityIcons/citrine/Crystallize130xWhite.webp"
    },{
        name: "Ember",
        health: 100,
        shield: 100,
        armor: 125,
        sprintSpeed: 1.1,
        energy: 150,
        duration: 100,
        efficiency: 100,
        range: 100,
        strength: 100,
        ability1: "/abilityIcons/ember/EmberFireBall.png.webp",
        ability2: "/abilityIcons/ember/EmberImmolation.png.webp",
        ability3: "/abilityIcons/ember/EmberFireBlast.png.webp",
        ability4: "/abilityIcons/ember/EmberInferno.png.webp"
    },{
        name: "Ember Prime",
        health: 100,
        shield: 125,
        armor: 150,
        sprintSpeed: 1.1,
        energy: 150,
        duration: 100,
        efficiency: 100,
        range: 100,
        strength: 100,
        ability1: "/abilityIcons/ember/EmberFireBall.png.webp",
        ability2: "/abilityIcons/ember/EmberImmolation.png.webp",
        ability3: "/abilityIcons/ember/EmberFireBlast.png.webp",
        ability4: "/abilityIcons/ember/EmberInferno.png.webp"
    },{
        name: "Equinox",
        health: 100,
        shield: 100,
        armor: 125,
        sprintSpeed: 1.15,
        energy: 150,
        duration: 100,
        efficiency: 100,
        range: 100,
        strength: 100,
        ability1: "/abilityIcons/equinox/YinYangTargetCalm.png.webp",
        ability2: "/abilityIcons/equinox/YinYangSwitch.png.webp",
        ability3: "/abilityIcons/equinox/YinYangAuraEnemyDamage.png.webp",
        ability4: "/abilityIcons/equinox/YinYangBlastHeal.png.webp"
    },{
        name: "Equinox Prime",
        health: 125,
        shield: 100,
        armor: 150,
        sprintSpeed: 1.15,
        energy: 165,
        duration: 100,
        efficiency: 100,
        range: 100,
        strength: 100,
        ability1: "/abilityIcons/equinox/YinYangTargetCalm.png.webp",
        ability2: "/abilityIcons/equinox/YinYangSwitch.png.webp",
        ability3: "/abilityIcons/equinox/YinYangAuraEnemyDamage.png.webp",
        ability4: "/abilityIcons/equinox/YinYangBlastHeal.png.webp"
    },{
        name: "Excalibur",
        health: 100,
        shield: 100,
        armor: 225,
        sprintSpeed: 1,
        energy: 100,
        duration: 100,
        efficiency: 100,
        range: 100,
        strength: 100,
        ability1: "/abilityIcons/excalibur/Power04.png.webp",
        ability2: "/abilityIcons/excalibur/Power01.png.webp",
        ability3: "/abilityIcons/excalibur/Power03.png.webp",
        ability4: "/abilityIcons/excalibur/ExcaliburSwordOfDoom.png.webp"
    },{
        name: "Excalibur Prime",
        health: 100,
        shield: 100,
        armor: 300,
        sprintSpeed: 1,
        energy: 150,
        duration: 100,
        efficiency: 100,
        range: 100,
        strength: 100,
        ability1: "/abilityIcons/excalibur/Power04.png.webp",
        ability2: "/abilityIcons/excalibur/Power01.png.webp",
        ability3: "/abilityIcons/excalibur/Power03.png.webp",
        ability4: "/abilityIcons/excalibur/ExcaliburSwordOfDoom.png.webp"
    },{
        name: "Excalibur Umbra",
        health: 100,
        shield: 100,
        armor: 300,
        sprintSpeed: 1,
        energy: 150,
        duration: 100,
        efficiency: 100,
        range: 100,
        strength: 100,
        ability1: "/abilityIcons/excalibur-umbra/Power04.png.webp",
        ability2: "/abilityIcons/excalibur-umbra/ExcaliburUmbraRoar.png.webp",
        ability3: "/abilityIcons/excalibur-umbra/Power03.png.webp",
        ability4: "/abilityIcons/excalibur-umbra/ExcaliburSwordOfDoom.png.webp"
    },{
        name: "Frost",
        health: 100,
        shield: 150,
        armor: 300,
        sprintSpeed: 0.95,
        energy: 100,
        duration: 100,
        efficiency: 100,
        range: 100,
        strength: 100,
        ability1: "/abilityIcons/frost/FrostFreeze.png.webp",
        ability2: "/abilityIcons/frost/FrostIceWave.png.webp",
        ability3: "/abilityIcons/frost/FrostSnowGlobe.png.webp",
        ability4: "/abilityIcons/frost/FrostAvalanche.png.webp"
    },{
        name: "Frost Prime",
        health: 100,
        shield: 175,
        armor: 300,
        sprintSpeed: 0.95,
        energy: 100,
        duration: 100,
        efficiency: 100,
        range: 100,
        strength: 100,
        ability1: "/abilityIcons/frost/FrostFreeze.png.webp",
        ability2: "/abilityIcons/frost/FrostIceWave.png.webp",
        ability3: "/abilityIcons/frost/FrostSnowGlobe.png.webp",
        ability4: "/abilityIcons/frost/FrostAvalanche.png.webp"
    },{
        name: "Gara",
        health: 100,
        shield: 100,
        armor: 150,
        sprintSpeed: 1.15,
        energy: 150,
        duration: 100,
        efficiency: 100,
        range: 100,
        strength: 100,
        ability1: "/abilityIcons/gara/GlassShank.png.webp",
        ability2: "/abilityIcons/gara/GlassShatteredAura.png.webp",
        ability3: "/abilityIcons/gara/GlassFragmentedReality.png.webp",
        ability4: "/abilityIcons/gara/GlassRing.png.webp"
    },{
        name: "Gara Prime",
        health: 120,
        shield: 100,
        armor: 190,
        sprintSpeed: 1.15,
        energy: 150,
        duration: 100,
        efficiency: 100,
        range: 100,
        strength: 100,
        ability1: "/abilityIcons/gara/GlassShank.png.webp",
        ability2: "/abilityIcons/gara/GlassShatteredAura.png.webp",
        ability3: "/abilityIcons/gara/GlassFragmentedReality.png.webp",
        ability4: "/abilityIcons/gara/GlassRing.png.webp"
    },{
        name: "Garuda",
        health: 100,
        shield: 100,
        armor: 300,
        sprintSpeed: 1,
        energy: 120,
        duration: 100,
        efficiency: 100,
        range: 100,
        strength: 100,
        ability1: "/abilityIcons/garuda/GarudaMeatShield.png.webp",
        ability2: "/abilityIcons/garuda/GarudaSanguineSiphon.png.webp",
        ability3: "/abilityIcons/garuda/GarudaBloodSunder.png.webp",
        ability4: "/abilityIcons/garuda/GarudaBoneZone.png.webp"
    },{
        name: "Garuda Prime",
        health: 100,
        shield: 100,
        armor: 400,
        sprintSpeed: 1,
        energy: 160,
        duration: 100,
        efficiency: 100,
        range: 100,
        strength: 100,
        ability1: "/abilityIcons/garuda/GarudaMeatShield.png.webp",
        ability2: "/abilityIcons/garuda/GarudaSanguineSiphon.png.webp",
        ability3: "/abilityIcons/garuda/GarudaBloodSunder.png.webp",
        ability4: "/abilityIcons/garuda/GarudaBoneZone.png.webp"
    },{
        name: "Gauss",
        health: 100,
        shield: 150,
        armor: 175,
        sprintSpeed: 1.4,
        energy: 150,
        duration: 100,
        efficiency: 100,
        range: 100,
        strength: 100,
        ability1: "/abilityIcons/gauss/RunnerMachRush.png.webp",
        ability2: "/abilityIcons/gauss/RunnerKineticPlating.png.webp",
        ability3: "/abilityIcons/gauss/RunnerEnergyTransfer.png.webp",
        ability4: "/abilityIcons/gauss/RunnerRedline.png.webp"
    },{
        name: "Grendel",
        health: 350,
        shield: 25,
        armor: 350,
        sprintSpeed: 0.95,
        energy: 150,
        duration: 100,
        efficiency: 100,
        range: 100,
        strength: 100,
        ability1: "/abilityIcons/grendel/GrendelDevour.png.webp",
        ability2: "/abilityIcons/grendel/GrendelConsume.png.webp",
        ability3: "/abilityIcons/grendel/GrendelBellyBowling.png.webp",
        ability4: "/abilityIcons/grendel/GrendelRegurgitate.png.webp"
    },{
        name: "Gyre",
        health: 100,
        shield: 175,
        armor: 100,
        sprintSpeed: 1,
        energy: 160,
        duration: 100,
        efficiency: 100,
        range: 100,
        strength: 100,
        ability1: "/abilityIcons/gyre/GyrePulse.png.webp",
        ability2: "/abilityIcons/gyre/GyreSphere.png.webp",
        ability3: "/abilityIcons/gyre/GyreEnergized.png.webp",
        ability4: "/abilityIcons/gyre/GyreOvercharged.png.webp"
    },{
        name: "Harrow",
        health: 100,
        shield: 150,
        armor: 175,
        sprintSpeed: 1,
        energy: 100,
        duration: 100,
        efficiency: 100,
        range: 100,
        strength: 100,
        ability1: "/abilityIcons/harrow/PriestCondemn.png.webp",
        ability2: "/abilityIcons/harrow/PriestPenance.png.webp",
        ability3: "/abilityIcons/harrow/PriestRavage.png.webp",
        ability4: "/abilityIcons/harrow/PriestPact.png.webp"
    },{
        name: "Harrow Prime",
        health: 100,
        shield: 200,
        armor: 175,
        sprintSpeed: 1,
        energy: 125,
        duration: 100,
        efficiency: 100,
        range: 100,
        strength: 100,
        ability1: "/abilityIcons/harrow/PriestCondemn.png.webp",
        ability2: "/abilityIcons/harrow/PriestPenance.png.webp",
        ability3: "/abilityIcons/harrow/PriestRavage.png.webp",
        ability4: "/abilityIcons/harrow/PriestPact.png.webp"
    },{
        name: "Hildryn",
        health: 75,
        shield: 450,
        armor: 300,
        sprintSpeed: 1,
        energy: 0,
        duration: 100,
        efficiency: 100,
        range: 100,
        strength: 100,
        ability1: "/abilityIcons/hildryn/HildrynBalefire.png.webp",
        ability2: "/abilityIcons/hildryn/HildrynShieldPillage.png.webp",
        ability3: "/abilityIcons/hildryn/HildrynHaven.png.webp",
        ability4: "/abilityIcons/hildryn/HildrynWingedDeath.png.webp"
    },{
        name: "Hydroid",
        health: 100,
        shield: 125,
        armor: 225,
        sprintSpeed: 1.05,
        energy: 125,
        duration: 100,
        efficiency: 100,
        range: 100,
        strength: 100,
        ability1: "/abilityIcons/hydroid/PirateCannonBarage.png.webp",
        ability2: "/abilityIcons/hydroid/PirateTidalWave.png.webp",
        ability3: "/abilityIcons/hydroid/PirateLiquefy.png.webp",
        ability4: "/abilityIcons/hydroid/PirateKraken.png.webp"
    },{
        name: "Hydroid Prime",
        health: 100,
        shield: 175,
        armor: 275,
        sprintSpeed: 1.05,
        energy: 150,
        duration: 100,
        efficiency: 100,
        range: 100,
        strength: 100,
        ability1: "/abilityIcons/hydroid/PirateCannonBarage.png.webp",
        ability2: "/abilityIcons/hydroid/PirateTidalWave.png.webp",
        ability3: "/abilityIcons/hydroid/PirateLiquefy.png.webp",
        ability4: "/abilityIcons/hydroid/PirateKraken.png.webp"
    },{
        name: "Inaros",
        health: 550,
        shield: 0,
        armor: 225,
        sprintSpeed: 1,
        energy: 100,
        duration: 100,
        efficiency: 100,
        range: 100,
        strength: 100,
        ability1: "/abilityIcons/inaros/SandmanBlast.png.webp",
        ability2: "/abilityIcons/inaros/SandmanDevour.png.webp",
        ability3: "/abilityIcons/inaros/SandmanStorm.png.webp",
        ability4: "/abilityIcons/inaros/SandmanSwarm.png.webp"
    },{
        name: "Inaros Prime",
        health: 575,
        shield: 0,
        armor: 225,
        sprintSpeed: 1.05,
        energy: 125,
        duration: 100,
        efficiency: 100,
        range: 100,
        strength: 100,
        ability1: "/abilityIcons/inaros/SandmanBlast.png.webp",
        ability2: "/abilityIcons/inaros/SandmanDevour.png.webp",
        ability3: "/abilityIcons/inaros/SandmanStorm.png.webp",
        ability4: "/abilityIcons/inaros/SandmanSwarm.png.webp"
    },{
        name: "Ivara",
        health: 75,
        shield: 100,
        armor: 100,
        sprintSpeed: 1.15,
        energy: 175,
        duration: 100,
        efficiency: 100,
        range: 100,
        strength: 100,
        ability1: "/abilityIcons/ivara/RangerVersatileQuiver.png.webp",
        ability2: "/abilityIcons/ivara/RangerAfterTouch.png.webp",
        ability3: "/abilityIcons/ivara/RangerSteal.png.webp",
        ability4: "/abilityIcons/ivara/RangerExaltedBow.png.webp"
    },{
        name: "Ivara Prime",
        health: 75,
        shield: 150,
        armor: 125,
        sprintSpeed: 1.2,
        energy: 200,
        duration: 100,
        efficiency: 100,
        range: 100,
        strength: 100,
        ability1: "/abilityIcons/ivara/RangerVersatileQuiver.png.webp",
        ability2: "/abilityIcons/ivara/RangerAfterTouch.png.webp",
        ability3: "/abilityIcons/ivara/RangerSteal.png.webp",
        ability4: "/abilityIcons/ivara/RangerExaltedBow.png.webp"
    },{
        name: "Khora",
        health: 125,
        shield: 100,
        armor: 275,
        sprintSpeed: 1.05,
        energy: 125,
        duration: 100,
        efficiency: 100,
        range: 100,
        strength: 100,
        ability1: "/abilityIcons/khora/KhoraCrack.png.webp",
        ability2: "/abilityIcons/khora/KhoraAllTiedUp.png.webp",
        ability3: "/abilityIcons/khora/KhoraSummon.png.webp",
        ability4: "/abilityIcons/khora/KhoraStrangleDome.png.webp"
    },{
        name: "Khora Prime",
        health: 125,
        shield: 125,
        armor: 325,
        sprintSpeed: 1.05,
        energy: 150,
        duration: 100,
        efficiency: 100,
        range: 100,
        strength: 100,
        ability1: "/abilityIcons/khora/KhoraCrack.png.webp",
        ability2: "/abilityIcons/khora/KhoraAllTiedUp.png.webp",
        ability3: "/abilityIcons/khora/KhoraSummon.png.webp",
        ability4: "/abilityIcons/khora/KhoraStrangleDome.png.webp"
    },{
        name: "Lavos",
        health: 200,
        shield: 100,
        armor: 450,
        sprintSpeed: 1.15,
        energy: 0,
        duration: 100,
        efficiency: 100,
        range: 100,
        strength: 100,
        ability1: "/abilityIcons/lavos/AlchemistSerpent.png.webp",
        ability2: "/abilityIcons/lavos/AlchemistRush.png.webp",
        ability3: "/abilityIcons/lavos/AlchemistTransmuter.png.webp",
        ability4: "/abilityIcons/lavos/AlchemistDistill.png.webp"
    },{
        name: "Limbo",
        health: 100,
        shield: 75,
        armor: 100,
        sprintSpeed: 1.15,
        energy: 150,
        duration: 100,
        efficiency: 100,
        range: 100,
        strength: 100,
        ability1: "/abilityIcons/limbo/LimboBanish.png.webp",
        ability2: "/abilityIcons/limbo/LimboRiftWalk.png.webp",
        ability3: "/abilityIcons/limbo/LimboVolatile.png.webp",
        ability4: "/abilityIcons/limbo/LimboTearInSpace.png.webp"
    },{
        name: "Limbo Prime",
        health: 100,
        shield: 100,
        armor: 125,
        sprintSpeed: 1.15,
        energy: 175,
        duration: 100,
        efficiency: 100,
        range: 100,
        strength: 100,
        ability1: "/abilityIcons/limbo/LimboBanish.png.webp",
        ability2: "/abilityIcons/limbo/LimboRiftWalk.png.webp",
        ability3: "/abilityIcons/limbo/LimboVolatile.png.webp",
        ability4: "/abilityIcons/limbo/LimboTearInSpace.png.webp"
    },{
        name: "Loki",
        health: 75,
        shield: 75,
        armor: 100,
        sprintSpeed: 1.25,
        energy: 150,
        duration: 100,
        efficiency: 100,
        range: 100,
        strength: 100,
        ability1: "/abilityIcons/loki/LokiDecoy.png.webp",
        ability2: "/abilityIcons/loki/LokiInvisibility.png.webp",
        ability3: "/abilityIcons/loki/LokiSwitchTeleport.png.webp",
        ability4: "/abilityIcons/loki/LokiRadialDisarm.png.webp"
    },{
        name: "Loki Prime",
        health: 75,
        shield: 75,
        armor: 125,
        sprintSpeed: 1.25,
        energy: 175,
        duration: 100,
        efficiency: 100,
        range: 100,
        strength: 100,
        ability1: "/abilityIcons/loki/LokiDecoy.png.webp",
        ability2: "/abilityIcons/loki/LokiInvisibility.png.webp",
        ability3: "/abilityIcons/loki/LokiSwitchTeleport.png.webp",
        ability4: "/abilityIcons/loki/LokiRadialDisarm.png.webp"
    },{
        name: "Mag",
        health: 75,
        shield: 150,
        armor: 100,
        sprintSpeed: 1,
        energy: 125,
        duration: 100,
        efficiency: 100,
        range: 100,
        strength: 100,
        ability1: "/abilityIcons/mag/MagPull.png.webp",
        ability2: "/abilityIcons/mag/MagMagnetize.png.webp",
        ability3: "/abilityIcons/mag/MagShieldRenew.png.webp",
        ability4: "/abilityIcons/mag/MagCrush.png.webp"
    },{
        name: "Mag Prime",
        health: 100,
        shield: 150,
        armor: 125,
        sprintSpeed: 1,
        energy: 175,
        duration: 100,
        efficiency: 100,
        range: 100,
        strength: 100,
        ability1: "/abilityIcons/mag/MagPull.png.webp",
        ability2: "/abilityIcons/mag/MagMagnetize.png.webp",
        ability3: "/abilityIcons/mag/MagShieldRenew.png.webp",
        ability4: "/abilityIcons/mag/MagCrush.png.webp"
    },{
        name: "Mesa",
        health: 125,
        shield: 75,
        armor: 100,
        sprintSpeed: 1.1,
        energy: 100,
        duration: 100,
        efficiency: 100,
        range: 100,
        strength: 100,
        ability1: "/abilityIcons/mesa/GunslingerBallisticBattery.png.webp",
        ability2: "/abilityIcons/mesa/GunslingerRussianRoulette.png.webp",
        ability3: "/abilityIcons/mesa/GunslingerRicochetArmour.png.webp",
        ability4: "/abilityIcons/mesa/GunslingerGunFu.png.webp"
    },{
        name: "Mesa Prime",
        health: 135,
        shield: 75,
        armor: 125,
        sprintSpeed: 1.1,
        energy: 125,
        duration: 100,
        efficiency: 100,
        range: 100,
        strength: 100,
        ability1: "/abilityIcons/mesa/GunslingerBallisticBattery.png.webp",
        ability2: "/abilityIcons/mesa/GunslingerRussianRoulette.png.webp",
        ability3: "/abilityIcons/mesa/GunslingerRicochetArmour.png.webp",
        ability4: "/abilityIcons/mesa/GunslingerGunFu.png.webp"
    },{
        name: "Mirage",
        health: 80,
        shield: 80,
        armor: 100,
        sprintSpeed: 1.2,
        energy: 150,
        duration: 100,
        efficiency: 100,
        range: 100,
        strength: 100,
        ability1: "/abilityIcons/mirage/HarlequinReflection.png.webp",
        ability2: "/abilityIcons/mirage/HarlequinDeadlyTrap.png.webp",
        ability3: "/abilityIcons/mirage/HarlequinLightDark.png.webp",
        ability4: "/abilityIcons/mirage/HarlequinPrism.png.webp"
    },{
        name: "Mirage Prime",
        health: 80,
        shield: 110,
        armor: 175,
        sprintSpeed: 1.2,
        energy: 125,
        duration: 100,
        efficiency: 100,
        range: 100,
        strength: 100,
        ability1: "/abilityIcons/mirage/HarlequinReflection.png.webp",
        ability2: "/abilityIcons/mirage/HarlequinDeadlyTrap.png.webp",
        ability3: "/abilityIcons/mirage/HarlequinLightDark.png.webp",
        ability4: "/abilityIcons/mirage/HarlequinPrism.png.webp"
    },{
        name: "Nekros",
        health: 100,
        shield: 90,
        armor: 100,
        sprintSpeed: 1.1,
        energy: 100,
        duration: 100,
        efficiency: 100,
        range: 100,
        strength: 100,
        ability1: "/abilityIcons/nekros/NecroSoulPunch.png.webp",
        ability2: "/abilityIcons/nekros/NecroTerrorTotem.png.webp",
        ability3: "/abilityIcons/nekros/NecroSearchTheDead.png.webp",
        ability4: "/abilityIcons/nekros/NecroCloneTheDead.png.webp"
    },{
        name: "Nekros Prime",
        health: 100,
        shield: 150,
        armor: 125,
        sprintSpeed: 1.1,
        energy: 125,
        duration: 100,
        efficiency: 100,
        range: 100,
        strength: 100,
        ability1: "/abilityIcons/nekros/NecroSoulPunch.png.webp",
        ability2: "/abilityIcons/nekros/NecroTerrorTotem.png.webp",
        ability3: "/abilityIcons/nekros/NecroSearchTheDead.png.webp",
        ability4: "/abilityIcons/nekros/NecroCloneTheDead.png.webp"
    },{
        name: "Nezha",
        health: 125,
        shield: 50,
        armor: 190,
        sprintSpeed: 1.15,
        energy: 150,
        duration: 100,
        efficiency: 100,
        range: 100,
        strength: 100,
        ability1: "/abilityIcons/nezha/NezhaTrail.png.webp",
        ability2: "/abilityIcons/nezha/NezhaRing.png.webp",
        ability3: "/abilityIcons/nezha/NeshaSash.png.webp",
        ability4: "/abilityIcons/nezha/NezhaSpear.png.webp"
    },{
        name: "Nezha Prime",
        health: 125,
        shield: 50,
        armor: 250,
        sprintSpeed: 1.2,
        energy: 150,
        duration: 100,
        efficiency: 100,
        range: 100,
        strength: 100,
        ability1: "/abilityIcons/nezha/NezhaTrail.png.webp",
        ability2: "/abilityIcons/nezha/NezhaRing.png.webp",
        ability3: "/abilityIcons/nezha/NeshaSash.png.webp",
        ability4: "/abilityIcons/nezha/NezhaSpear.png.webp"
    },{
        name: "Nidus",
        health: 150,
        shield: 0,
        armor: 300,
        sprintSpeed: 1,
        energy: 100,
        duration: 100,
        efficiency: 100,
        range: 100,
        strength: 100,
        ability1: "/abilityIcons/nidus/InfestedRupture.png.webp",
        ability2: "/abilityIcons/nidus/InfestedTendrils.png.webp",
        ability3: "/abilityIcons/nidus/InfestedSymbioticLink.png.webp",
        ability4: "/abilityIcons/nidus/InfestedInfest.png.webp"
    },{
        name: "Nidus Prime",
        health: 175,
        shield: 0,
        armor: 350,
        sprintSpeed: 1,
        energy: 125,
        duration: 100,
        efficiency: 100,
        range: 100,
        strength: 100,
        ability1: "/abilityIcons/nidus/InfestedRupture.png.webp",
        ability2: "/abilityIcons/nidus/InfestedTendrils.png.webp",
        ability3: "/abilityIcons/nidus/InfestedSymbioticLink.png.webp",
        ability4: "/abilityIcons/nidus/InfestedInfest.png.webp"
    },{
        name: "Nova",
        health: 100,
        shield: 75,
        armor: 100,
        sprintSpeed: 1.2,
        energy: 150,
        duration: 100,
        efficiency: 100,
        range: 100,
        strength: 100,
        ability1: "/abilityIcons/nova/NovaNullStar.png.webp",
        ability2: "/abilityIcons/nova/NovaAntimatterDrop.png.webp",
        ability3: "/abilityIcons/nova/NovaWormHole.png.webp",
        ability4: "/abilityIcons/nova/NovaMolecularPrime.png.webp"
    },{
        name: "Nova Prime",
        health: 100,
        shield: 100,
        armor: 125,
        sprintSpeed: 1.2,
        energy: 175,
        duration: 100,
        efficiency: 100,
        range: 100,
        strength: 100,
        ability1: "/abilityIcons/nova/NovaNullStar.png.webp",
        ability2: "/abilityIcons/nova/NovaAntimatterDrop.png.webp",
        ability3: "/abilityIcons/nova/NovaWormHole.png.webp",
        ability4: "/abilityIcons/nova/NovaMolecularPrime.png.webp"
    },{
        name: "Nyx",
        health: 100,
        shield: 100,
        armor: 100,
        sprintSpeed: 1.1,
        energy: 150,
        duration: 100,
        efficiency: 100,
        range: 100,
        strength: 100,
        ability1: "/abilityIcons/nyx/NyxMindControl.png.webp",
        ability2: "/abilityIcons/nyx/NyxPsychicBolts.png.webp",
        ability3: "/abilityIcons/nyx/NyxChaos.png.webp",
        ability4: "/abilityIcons/nyx/NyxAbsorb.png.webp"
    },{
        name: "Nyx Prime",
        health: 100,
        shield: 125,
        armor: 125,
        sprintSpeed: 1.125,
        energy: 150,
        duration: 100,
        efficiency: 100,
        range: 100,
        strength: 100,
        ability1: "/abilityIcons/nyx/NyxMindControl.png.webp",
        ability2: "/abilityIcons/nyx/NyxPsychicBolts.png.webp",
        ability3: "/abilityIcons/nyx/NyxChaos.png.webp",
        ability4: "/abilityIcons/nyx/NyxAbsorb.png.webp"
    },{
        name: "Oberon",
        health: 125,
        shield: 100,
        armor: 175,
        sprintSpeed: 1,
        energy: 150,
        duration: 100,
        efficiency: 100,
        range: 100,
        strength: 100,
        ability1: "/abilityIcons/oberon/PaladinSmite.png.webp",
        ability2: "/abilityIcons/oberon/PaladinHallowedGround.png.webp",
        ability3: "/abilityIcons/oberon/PaladinRenewal.png.webp",
        ability4: "/abilityIcons/oberon/PaladinReckoning.png.webp"
    },{
        name: "Oberon Prime",
        health: 125,
        shield: 100,
        armor: 225,
        sprintSpeed: 1,
        energy: 175,
        duration: 100,
        efficiency: 100,
        range: 100,
        strength: 100,
        ability1: "/abilityIcons/oberon/PaladinSmite.png.webp",
        ability2: "/abilityIcons/oberon/PaladinHallowedGround.png.webp",
        ability3: "/abilityIcons/oberon/PaladinRenewal.png.webp",
        ability4: "/abilityIcons/oberon/PaladinReckoning.png.webp"
    },{
        name: "Octavia",
        health: 100,
        shield: 75,
        armor: 150,
        sprintSpeed: 1.05,
        energy: 150,
        duration: 100,
        efficiency: 100,
        range: 100,
        strength: 100,
        ability1: "/abilityIcons/octavia/BardMusicBox.png.webp",
        ability2: "/abilityIcons/octavia/BardPiedPiper.png.webp",
        ability3: "/abilityIcons/octavia/BardPumpJam.png.webp",
        ability4: "/abilityIcons/octavia/BardAmplifier.png.webp"
    },{
        name: "Octavia Prime",
        health: 100,
        shield: 100,
        armor: 150,
        sprintSpeed: 1.05,
        energy: 175,
        duration: 100,
        efficiency: 100,
        range: 100,
        strength: 100,
        ability1: "/abilityIcons/octavia/BardMusicBox.png.webp",
        ability2: "/abilityIcons/octavia/BardPiedPiper.png.webp",
        ability3: "/abilityIcons/octavia/BardPumpJam.png.webp",
        ability4: "/abilityIcons/octavia/BardAmplifier.png.webp"
    },{
        name: "Protea",
        health: 100,
        shield: 150,
        armor: 125,
        sprintSpeed: 1.2,
        energy: 150,
        duration: 100,
        efficiency: 100,
        range: 100,
        strength: 100,
        ability1: "/abilityIcons/protea/ProteaGrenadeFan.png.webp",
        ability2: "/abilityIcons/protea/ProteaBFG.png.webp",
        ability3: "/abilityIcons/protea/ProteaDispensary.png.webp",
        ability4: "/abilityIcons/protea/ProteaTemporalAnchor.png.webp"
    },{
        name: "Revenant",
        health: 100,
        shield: 225,
        armor: 125,
        sprintSpeed: 1,
        energy: 125,
        duration: 100,
        efficiency: 100,
        range: 100,
        strength: 100,
        ability1: "/abilityIcons/revenant/RevenantEnthrall.png.webp",
        ability2: "/abilityIcons/revenant/RevenantMesmerSkin.png.webp",
        ability3: "/abilityIcons/revenant/RevenantReave.png.webp",
        ability4: "/abilityIcons/revenant/RevenantDanseMacabre.png.webp"
    },{
        name: "Revenant Prime",
        health: 100,
        shield: 250,
        armor: 125,
        sprintSpeed: 1.1,
        energy: 150,
        duration: 100,
        efficiency: 100,
        range: 100,
        strength: 100,
        ability1: "/abilityIcons/revenant/RevenantEnthrall.png.webp",
        ability2: "/abilityIcons/revenant/RevenantMesmerSkin.png.webp",
        ability3: "/abilityIcons/revenant/RevenantReave.png.webp",
        ability4: "/abilityIcons/revenant/RevenantDanseMacabre.png.webp"
    },{
        name: "Rhino",
        health: 100,
        shield: 150,
        armor: 225,
        sprintSpeed: 0.95,
        energy: 100,
        duration: 100,
        efficiency: 100,
        range: 100,
        strength: 100,
        ability1: "/abilityIcons/rhino/RhinoDash.png.webp",
        ability2: "/abilityIcons/rhino/RhinoIronSkin.png.webp",
        ability3: "/abilityIcons/rhino/RhinoRadialBlast.png.webp",
        ability4: "/abilityIcons/rhino/RhinoStomp.png.webp"
    },{
        name: "Rhino Prime",
        health: 100,
        shield: 150,
        armor: 275,
        sprintSpeed: 1,
        energy: 100,
        duration: 100,
        efficiency: 100,
        range: 100,
        strength: 100,
        ability1: "/abilityIcons/rhino/RhinoDash.png.webp",
        ability2: "/abilityIcons/rhino/RhinoIronSkin.png.webp",
        ability3: "/abilityIcons/rhino/RhinoRadialBlast.png.webp",
        ability4: "/abilityIcons/rhino/RhinoStomp.png.webp"
    },{
        name: "Saryn",
        health: 125,
        shield: 100,
        armor: 225,
        sprintSpeed: 0.95,
        energy: 150,
        duration: 100,
        efficiency: 100,
        range: 100,
        strength: 100,
        ability1: "/abilityIcons/saryn/SarynVenom.png.webp",
        ability2: "/abilityIcons/saryn/SarynMoult.png.webp",
        ability3: "/abilityIcons/saryn/SarynContagion.png.webp",
        ability4: "/abilityIcons/saryn/SarynMiasma.png.webp"
    },{
        name: "Saryn Prime",
        health: 125,
        shield: 100,
        armor: 300,
        sprintSpeed: 1,
        energy: 200,
        duration: 100,
        efficiency: 100,
        range: 100,
        strength: 100,
        ability1: "/abilityIcons/saryn/SarynVenom.png.webp",
        ability2: "/abilityIcons/saryn/SarynMoult.png.webp",
        ability3: "/abilityIcons/saryn/SarynContagion.png.webp",
        ability4: "/abilityIcons/saryn/SarynMiasma.png.webp"
    },{
        name: "Sevagoth",
        health: 100,
        shield: 90,
        armor: 150,
        sprintSpeed: 0.95,
        energy: 125,
        duration: 100,
        efficiency: 100,
        range: 100,
        strength: 100,
        ability1: "/abilityIcons/sevagoth/WraithReap.png.webp",
        ability2: "/abilityIcons/sevagoth/WraithSow.png.webp",
        ability3: "/abilityIcons/sevagoth/WraithGloom.png.webp",
        ability4: "/abilityIcons/sevagoth/WraithDontFearTheReaper.png.webp"
    },{
        name: "Styanax",
        health: 100,
        shield: 250,
        armor: 250,
        sprintSpeed: 1,
        energy: 150,
        duration: 100,
        efficiency: 100,
        range: 100,
        strength: 100,
        ability1: "/abilityIcons/styanax/AxiosJavelin130xWhite.webp",
        ability2: "/abilityIcons/styanax/TharrosStrike130xWhite.webp",
        ability3: "/abilityIcons/styanax/RallyPoint130xWhite.webp",
        ability4: "/abilityIcons/styanax/FinalStand130xWhite.webp"
    },{
        name: "Titania",
        health: 100,
        shield: 100,
        armor: 100,
        sprintSpeed: 1,
        energy: 150,
        duration: 100,
        efficiency: 100,
        range: 100,
        strength: 100,
        ability1: "/abilityIcons/titania/FaerieDust.png.webp",
        ability2: "/abilityIcons/titania/FaerieSoul.png.webp",
        ability3: "/abilityIcons/titania/FaerieLamp.png.webp",
        ability4: "/abilityIcons/titania/FaerieShrink.png.webp"
    },{
        name: "Titania Prime",
        health: 125,
        shield: 100,
        armor: 125,
        sprintSpeed: 1,
        energy: 175,
        duration: 100,
        efficiency: 100,
        range: 100,
        strength: 100,
        ability1: "/abilityIcons/titania/FaerieDust.png.webp",
        ability2: "/abilityIcons/titania/FaerieSoul.png.webp",
        ability3: "/abilityIcons/titania/FaerieLamp.png.webp",
        ability4: "/abilityIcons/titania/FaerieShrink.png.webp"
    },{
        name: "Trinity",
        health: 100,
        shield: 100,
        armor: 100,
        sprintSpeed: 1,
        energy: 150,
        duration: 100,
        efficiency: 100,
        range: 100,
        strength: 100,
        ability1: "/abilityIcons/trinity/TrinityWellOfLife.png.webp",
        ability2: "/abilityIcons/trinity/TrinityEnergyVampire.png.webp",
        ability3: "/abilityIcons/trinity/TrinityLink.png.webp",
        ability4: "/abilityIcons/trinity/TrinityBlessing.png.webp"
    },{
        name: "Trinity Prime",
        health: 100,
        shield: 150,
        armor: 125,
        sprintSpeed: 1.1,
        energy: 150,
        duration: 100,
        efficiency: 100,
        range: 100,
        strength: 100,
        ability1: "/abilityIcons/trinity/TrinityWellOfLife.png.webp",
        ability2: "/abilityIcons/trinity/TrinityEnergyVampire.png.webp",
        ability3: "/abilityIcons/trinity/TrinityLink.png.webp",
        ability4: "/abilityIcons/trinity/TrinityBlessing.png.webp"
    },{
        name: "Valkyr",
        health: 100,
        shield: 50,
        armor: 600,
        sprintSpeed: 1.1,
        energy: 100,
        duration: 100,
        efficiency: 100,
        range: 100,
        strength: 100,
        ability1: "/abilityIcons/valkyr/BerserkerGrapplingHook.png.webp",
        ability2: "/abilityIcons/valkyr/BerserkerScream.png.webp",
        ability3: "/abilityIcons/valkyr/BerserkerShieldBash.png.webp",
        ability4: "/abilityIcons/valkyr/BerserkerLastStand.png.webp"
    },{
        name: "Valkyr Prime",
        health: 100,
        shield: 50,
        armor: 700,
        sprintSpeed: 1.1,
        energy: 150,
        duration: 100,
        efficiency: 100,
        range: 100,
        strength: 100,
        ability1: "/abilityIcons/valkyr/BerserkerGrapplingHook.png.webp",
        ability2: "/abilityIcons/valkyr/BerserkerScream.png.webp",
        ability3: "/abilityIcons/valkyr/BerserkerShieldBash.png.webp",
        ability4: "/abilityIcons/valkyr/BerserkerLastStand.png.webp"
    },{
        name: "Vauban",
        health: 100,
        shield: 75,
        armor: 150,
        sprintSpeed: 1,
        energy: 150,
        duration: 100,
        efficiency: 100,
        range: 100,
        strength: 100,
        ability1: "/abilityIcons/vauban/VaubanTeslaDrones.png.webp",
        ability2: "/abilityIcons/vauban/VaubanMinelayer.png.webp",
        ability3: "/abilityIcons/vauban/VaubanOrbitalStrike.png.webp",
        ability4: "/abilityIcons/vauban/VaubanBastille.png.webp"
    },{
        name: "Vauban Prime",
        health: 100,
        shield: 100,
        armor: 200,
        sprintSpeed: 1,
        energy: 150,
        duration: 100,
        efficiency: 100,
        range: 100,
        strength: 100,
        ability1: "/abilityIcons/vauban/VaubanTeslaDrones.png.webp",
        ability2: "/abilityIcons/vauban/VaubanMinelayer.png.webp",
        ability3: "/abilityIcons/vauban/VaubanOrbitalStrike.png.webp",
        ability4: "/abilityIcons/vauban/VaubanBastille.png.webp"
    },{
        name: "Volt",
        health: 100,
        shield: 150,
        armor: 100,
        sprintSpeed: 1,
        energy: 100,
        duration: 100,
        efficiency: 100,
        range: 100,
        strength: 100,
        ability1: "/abilityIcons/volt/VoltChainLightning.png.webp",
        ability2: "/abilityIcons/volt/VoltSuperSpeed.png.webp",
        ability3: "/abilityIcons/volt/VoltShield.png.webp",
        ability4: "/abilityIcons/volt/VoltOverLoad.png.webp"
    },{
        name: "Volt Prime",
        health: 100,
        shield: 150,
        armor: 125,
        sprintSpeed: 1,
        energy: 200,
        duration: 100,
        efficiency: 100,
        range: 100,
        strength: 100,
        ability1: "/abilityIcons/volt/VoltChainLightning.png.webp",
        ability2: "/abilityIcons/volt/VoltSuperSpeed.png.webp",
        ability3: "/abilityIcons/volt/VoltShield.png.webp",
        ability4: "/abilityIcons/volt/VoltOverLoad.png.webp"
    },{
        name: "Voruna",
        health: 150,
        shield: 100,
        armor: 190,
        sprintSpeed: 0.95,
        energy: 100,
        duration: 100,
        efficiency: 100,
        range: 100,
        strength: 100,
        ability1: "/abilityIcons/voruna/WerewolfShroud.png.webp",
        ability2: "/abilityIcons/voruna/WerewolfBite.png.webp",
        ability3: "/abilityIcons/voruna/WerewolfLeap.png.webp",
        ability4: "/abilityIcons/voruna/WerewolfHowl.png.webp"
    },{
        name: "Wisp",
        health: 100,
        shield: 75,
        armor: 175,
        sprintSpeed: 1.2,
        energy: 200,
        duration: 100,
        efficiency: 100,
        range: 100,
        strength: 100,
        ability1: "/abilityIcons/wisp/WispReservoir.png.webp",
        ability2: "/abilityIcons/wisp/WispList.png.webp",
        ability3: "/abilityIcons/wisp/WispHarnessTheLight.png.webp",
        ability4: "/abilityIcons/wisp/WispSolGate.png.webp"
    },{
        name: "Wukong",
        health: 150,
        shield: 100,
        armor: 250,
        sprintSpeed: 1,
        energy: 120,
        duration: 100,
        efficiency: 100,
        range: 100,
        strength: 100,
        ability1: "/abilityIcons/wukong/WukongHairOfTheKing.png.webp",
        ability2: "/abilityIcons/wukong/WukongCloudWalker.png.webp",
        ability3: "/abilityIcons/wukong/WukongDefy.png.webp",
        ability4: "/abilityIcons/wukong/WukongPrimalFury.png.webp"
    },{
        name: "Wukong Prime",
        health: 150,
        shield: 120,
        armor: 275,
        sprintSpeed: 1.05,
        energy: 130,
        duration: 100,
        efficiency: 100,
        range: 100,
        strength: 100,
        ability1: "/abilityIcons/wukong/WukongHairOfTheKing.png.webp",
        ability2: "/abilityIcons/wukong/WukongCloudWalker.png.webp",
        ability3: "/abilityIcons/wukong/WukongDefy.png.webp",
        ability4: "/abilityIcons/wukong/WukongPrimalFury.png.webp"
    },{
        name: "Xaku",
        health: 97,
        shield: 89,
        armor: 137,
        sprintSpeed: 1.02,
        energy: 153,
        duration: 100,
        efficiency: 100,
        range: 100,
        strength: 100,
        ability1: "/abilityIcons/xaku/BrokenFrameVoidRot.png.webp",
        ability2: "/abilityIcons/xaku/BrokenFrameTendrilGrasp.png.webp",
        ability3: "/abilityIcons/xaku/BrokenFrameEmbraceTheFallen.png.webp",
        ability4: "/abilityIcons/xaku/BrokenSelfDestruct.png.webp"
    },{
        name: "Yareli",
        health: 100,
        shield: 150,
        armor: 100,
        sprintSpeed: 1,
        energy: 200,
        duration: 100,
        efficiency: 100,
        range: 100,
        strength: 100,
        ability1: "/abilityIcons/yareli/YareliWaterTomb.png.webp",
        ability2: "/abilityIcons/yareli/YareliAquaBoard.png.webp",
        ability3: "/abilityIcons/yareli/YareliAqueousDisks.png.webp",
        ability4: "/abilityIcons/yareli/YareliCrushingWaters.png.webp"
    },{
        name: "Zephyr",
        health: 150,
        shield: 150,
        armor: 100,
        sprintSpeed: 1.15,
        energy: 100,
        duration: 100,
        efficiency: 100,
        range: 100,
        strength: 100,
        ability1: "/abilityIcons/zephyr/TenguTailWind.png.webp",
        ability2: "/abilityIcons/zephyr/TenguAirBurst.png.webp",
        ability3: "/abilityIcons/zephyr/TenguTurbulance.png.webp",
        ability4: "/abilityIcons/zephyr/TenguTornado.png.webp"
    },{
        name: "Zephyr Prime",
        health: 150,
        shield: 150,
        armor: 125,
        sprintSpeed: 1.2,
        energy: 150,
        duration: 100,
        efficiency: 100,
        range: 100,
        strength: 100,
        ability1: "/abilityIcons/zephyr/TenguTailWind.png.webp",
        ability2: "/abilityIcons/zephyr/TenguAirBurst.png.webp",
        ability3: "/abilityIcons/zephyr/TenguTurbulance.png.webp",
        ability4: "/abilityIcons/zephyr/TenguTornado.png.webp"
    }
]
let warframe = localStorage.getItem("warframe");
let warframePic = localStorage.getItem("warframe-pic");
for (let i = 0; i < warframes.length; i++){
    if (warframes[i].name === warframe){
        document.getElementById("warframe-name").firstElementChild.innerText = warframe;
        document.getElementById("warframe-img").src = warframePic;
        document.getElementById("health").innerText = warframes[i].health;
        document.getElementById("shield").innerText = warframes[i].shield;
        document.getElementById("armor").innerText = warframes[i].armor;
        document.getElementById("sprintspeed").innerText = warframes[i].sprintSpeed;
        document.getElementById("energy").innerText = warframes[i].energy;
        document.getElementById("ability-1-img").src = warframes[i].ability1;
        document.getElementById("ability-2-img").src = warframes[i].ability2;
        document.getElementById("ability-3-img").src = warframes[i].ability3;
        document.getElementById("ability-4-img").src = warframes[i].ability4;
        document.getElementById("duration").innerText = warframes[i].duration;
        document.getElementById("efficiency").innerText = warframes[i].efficiency;
        document.getElementById("range").innerText = warframes[i].range;
        document.getElementById("strength").innerText = warframes[i].strength;
        i = warframes.length;
    }
}

let buttons = document.getElementsByClassName("current-polarity");
for (let i = 0; i < buttons.length; i++){
    buttons[i].addEventListener("click", openDropdown);
}
function openDropdown(obj){
    let dropdown = obj.currentTarget.nextElementSibling; 
    if (dropdown.style.display === "flex"){
        dropdown.style.display = "none";
    }
    else{
        dropdown.style.display = "flex";
    }
}

let polarities = document.getElementsByClassName("polarity");
for (let i = 0; i < polarities.length; i++){
    polarities[i].addEventListener("click", changeCurrentPolarity);
}
function changeCurrentPolarity(obj){
    let polarity = obj.currentTarget;
    let polarityImage = polarity.firstElementChild.src;
    let dropdown = polarity.parentElement;
    let currentPolarity = dropdown.previousElementSibling;
    console.log(currentPolarity.innerText);
    if (polarityImage === undefined){
        if (currentPolarity.innerText !== "--"){
            updateFormaCount(false);
        }
        currentPolarity.innerHTML = "";
        currentPolarity.appendChild(document.createElement('p'));
        currentPolarity.firstElementChild.innerHTML = "--";
    }
    else{
        if (currentPolarity.innerText === "--"){
            updateFormaCount(true);
        }
        currentPolarity.innerHTML = "";
        currentPolarity.appendChild(document.createElement('img')).src 
        = polarityImage;
    }
    dropdown.style.display = "none";
}

function updateFormaCount(add){
    let formaCount = document.getElementById("forma-count");
    let originalCount = parseInt(formaCount.innerHTML);
    formaCount.innerHTML = "";
    if (add === true){
        formaCount.innerHTML = originalCount + 1;
    }
    else{
        formaCount.innerHTML = originalCount - 1;
    }
}

function updateProgressBar(){
    let progressBar = document.getElementById("progress-filled");
    let remaining = parseInt(document.getElementById("mod-remaining").innerText);
    let percent = (60 - remaining) * 1.67;
    progressBar.style.width = `${percent}%`;
}